<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Удалить новость';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Вы уверены, что хотите удалить '<?php echo $this->escapeHtml($news->title); ?>'?</p>
<?php
$url = $this->url('news', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $news->id; ?>">
    <input type="submit" name="del" value="Да">
    &nbsp;&nbsp;&nbsp;&nbsp;
    <input type=button value='Нет' onclick='location.href="<?php echo $this->url('news') ?>"'>
</div>
</form>