<?php
$csearch = isset($_COOKIE['search'])?$_COOKIE['search']:"";
$corder = isset($_COOKIE['order'])?(int)$_COOKIE['order']:-2;
$cspos = isset($_COOKIE['spos'])?(int)$_COOKIE['spos']:0;
$title = 'KMV Сайт Новостей' . (strlen($csearch)?" (результаты поиска)":"");
$this->headTitle($title);
global $isAdmin;
$pagecnt = $GLOBALS['pagecount'];
?>
<style>
    .ttho{
        <?php
        if( isset($_COOKIE['order']) ){
            echo "background: url(/img/order_" . (($corder<0)?"down":"up") . ".png) center right no-repeat lightyellow;";
        }
        ?>
    }
    .tth:hover, .ttho:hover{
        background-color: lightgreen;
        cursor: pointer;
    }
    tr:hover{
        background-color: oldlace;
        cursor: pointer;
    }        
    th{
        background-color: lightyellow;
        cursor: default;
    }
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if( $isAdmin ){ ?>
<p>
    <a href="<?php echo $this->url('news', array('action'=>'add'));?>">Добавить новость</a>
</p>
<?php } ?>    

<script>
function schg(el){ location.href = "<?php echo $this->url('news')?>?spos="+el.selectedIndex; }
function scrt(el, cnt){
    var ch, i;
    for( i=0; i<cnt; i++ ){
        ch = document.createElement("OPTION");
        el.appendChild(ch);
        ch.innerHTML = (i+1);
    }
    el.selectedIndex = <?php echo $cspos ?>;
}
</script>

<form id=sform action="<?php echo $this->url('news')?>?spos=0" method="POST" style="position: fixed; right: <?php echo $isAdmin?"150":"30"; ?>px; top: 15px; z-index: 2000;">
    <input type=text size=30 name="search" value="<?php echo htmlspecialchars($csearch) ?>" placeholder="Введите для поиска" title="Поиск проводится по заголовкам и текстам новостей"><input type=submit value="Поиск">
    <?php if( strlen($csearch) ){ ?>
    <input type=button value="Сброс" onclick="sform.children[0].value=''; sform.submit();" >
    <?php } ?>
</form>

<center style="padding-bottom: 10px">Страница <select id=selup onchange="schg(this)"></select> из <?php echo $pagecnt ?></center>

<table class="table">
<tr>
    <th class="tth<?php echo (abs($corder)==1)?"o":"" ?>" onclick="location.href='<?php echo $this->url('news') . "?order=" . (($corder==1)?-1:(($corder==-1)?0:1));?>'">Заголовок</th>
    <th class="tth<?php echo (abs($corder)==2)?"o":"" ?>" onclick="location.href='<?php echo $this->url('news') . "?order=" . (($corder==2)?-2:(($corder==-2)?0:2));?>'">Дата</th>
    <th>Короткий текст</th>
<?php if( $isAdmin ){ ?>
    <th>&nbsp;</th>
<?php } ?>    
</tr> 
<?php foreach ($news as $val) : ?>
<tr onclick="<?php if($isAdmin){ ?>if((event.target || event.srcElement).tagName=='TD') <?php } ?>location.href='<?php echo $this->url('news', array('action'=>'read', 'id' => $val->id)) ?>'">
    <td><?php echo $this->escapeHtml($val->title);?></td>
    <td><?php echo $this->escapeHtml($val->dt);?></td>
    <td><?php preg_match('#([\p{Z}\r]*[^\r\p{Z}]*){0,30}#m', $val->text, $matches);
              echo $this->escapeHtml($matches[0] . "...");?></td>
<?php if( $isAdmin ){ ?>
    <td align=center>
        <a href="<?php echo $this->url('news',
            array('action'=>'edit', 'id' => $val->id));?>">Изменить</a><br>
        <a href="<?php echo $this->url('news',
            array('action'=>'delete', 'id' => $val->id));?>">Удалить</a>
        <?php if( $val->ccnt>0 ){
            $comments = "комментари" . (($val->ccnt==1)?"й":(($val->ccnt%10>1 && $val->ccnt%10<5)?"я":"ев"));
            $need = "нужда" . (($val->ccnt==1)?"ется":"ются");
        ?>                    
         <br><span style="color: red" title="<?php echo $val->ccnt . " $comments $need" ?> в модерации">(<?php echo $val->ccnt; ?>)</span>
        <?php } ?>
    </td>
<?php } ?>    
</tr>
<?php endforeach; ?>
</table>

<center style="padding-top: 10px">Страница <select id=seldn onchange="schg(this)"></select> из <?php echo $pagecnt ?></center>

<script>
scrt(selup, <?php echo $pagecnt ?>); 
scrt(seldn, <?php echo $pagecnt ?>); 
</script>
